export interface CuratedDrug {
  id: string;
  name: string;
  generic: string;
  brand?: string;
  category: string;
  isFrid: boolean;
  fridClassId?: "bzd" | "antipsychotics" | "anticholinergics" | "tca" | "vasodilators" | "loop_diuretics" | "opioids" | "antiepileptics";
  defaultDose: string;
  doseOptions: string[];
  defaultFreq: string;
  freqOptions: string[];
  route: string;
  beersWarning?: string;
  acbScore?: number; // Anticholinergic cognitive burden
}

export const CURATED_DRUG_DATABASE: CuratedDrug[] = [
  // 1. Benzodiazepines & Z-Drugs (FRID: bzd)
  {
    id: "lorazepam",
    name: "Lorazepam",
    generic: "lorazepam",
    brand: "Ativan",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "1.0mg",
    doseOptions: ["0.5mg", "1.0mg", "2.0mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "BID", "TID", "PRN", "Q6H PRN"],
    route: "PO",
    beersWarning: "Avoid in older adults: high risk of cognitive impairment, delirium, falls, fractures, and motor vehicle crashes.",
  },
  {
    id: "diazepam",
    name: "Diazepam",
    generic: "diazepam",
    brand: "Valium",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "5mg",
    doseOptions: ["2mg", "5mg", "10mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "BID", "PRN"],
    route: "PO",
    beersWarning: "Long-acting benzodiazepine: severe accumulation risk in hepatic/renal decline.",
  },
  {
    id: "temazepam",
    name: "Temazepam",
    generic: "temazepam",
    brand: "Restoril",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "15mg",
    doseOptions: ["7.5mg", "15mg", "30mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "PRN"],
    route: "PO",
    beersWarning: "Intermediate-acting hypnotic with elevated next-day hangover and fall hazard.",
  },
  {
    id: "clonazepam",
    name: "Clonazepam",
    generic: "clonazepam",
    brand: "Klonopin",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "0.5mg",
    doseOptions: ["0.25mg", "0.5mg", "1.0mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "TID", "QHS"],
    route: "PO",
    beersWarning: "Potent high-affinity BZD: marked psychomotor ataxia.",
  },
  {
    id: "alprazolam",
    name: "Alprazolam",
    generic: "alprazolam",
    brand: "Xanax",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "0.5mg",
    doseOptions: ["0.25mg", "0.5mg", "1.0mg"],
    defaultFreq: "TID",
    freqOptions: ["TID", "BID", "PRN"],
    route: "PO",
    beersWarning: "Rapid peak onset and acute withdrawal rebound anxiety and postural sway.",
  },
  {
    id: "zolpidem",
    name: "Zolpidem",
    generic: "zolpidem",
    brand: "Ambien",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "10mg",
    doseOptions: ["5mg", "10mg", "6.25mg CR", "12.5mg CR"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "PRN QHS"],
    route: "PO",
    beersWarning: "Non-benzodiazepine receptor agonist (Z-drug): nocturnal wandering, sleepwalking, and emergency department visits.",
  },
  {
    id: "eszopiclone",
    name: "Eszopiclone",
    generic: "eszopiclone",
    brand: "Lunesta",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "2mg",
    doseOptions: ["1mg", "2mg", "3mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "PRN QHS"],
    route: "PO",
    beersWarning: "Prolonged elimination half-life in older adults (>9h).",
  },
  {
    id: "zaleplon",
    name: "Zaleplon",
    generic: "zaleplon",
    brand: "Sonata",
    category: "Benzodiazepines & Z-Drugs",
    isFrid: true,
    fridClassId: "bzd",
    defaultDose: "5mg",
    doseOptions: ["5mg", "10mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "PRN"],
    route: "PO",
    beersWarning: "Short-acting hypnotic; still induces nocturnal disorientation.",
  },

  // 2. Loop Diuretics (FRID: loop_diuretics)
  {
    id: "furosemide",
    name: "Furosemide",
    generic: "furosemide",
    brand: "Lasix",
    category: "Loop Diuretics",
    isFrid: true,
    fridClassId: "loop_diuretics",
    defaultDose: "40mg",
    doseOptions: ["20mg", "40mg", "80mg"],
    defaultFreq: "QAM",
    freqOptions: ["QAM", "BID", "Daily", "PRN"],
    route: "PO",
    beersWarning: "Rapid intravascular volume depletion and orthostatic hypotension. Nighttime dosing induces urgent nocturia falls.",
  },
  {
    id: "bumetanide",
    name: "Bumetanide",
    generic: "bumetanide",
    brand: "Bumex",
    category: "Loop Diuretics",
    isFrid: true,
    fridClassId: "loop_diuretics",
    defaultDose: "1mg",
    doseOptions: ["0.5mg", "1mg", "2mg"],
    defaultFreq: "QAM",
    freqOptions: ["QAM", "BID", "Daily"],
    route: "PO",
    beersWarning: "Potent loop diuretic: high risk of acute hypokalemia and orthostasis.",
  },
  {
    id: "torsemide",
    name: "Torsemide",
    generic: "torsemide",
    brand: "Demadex",
    category: "Loop Diuretics",
    isFrid: true,
    fridClassId: "loop_diuretics",
    defaultDose: "20mg",
    doseOptions: ["10mg", "20mg", "50mg"],
    defaultFreq: "QAM",
    freqOptions: ["QAM", "Daily"],
    route: "PO",
    beersWarning: "Long half-life loop diuretic: continuous volume contraction.",
  },

  // 3. Anticholinergics & Antihistamines (FRID: anticholinergics)
  {
    id: "diphenhydramine",
    name: "Diphenhydramine",
    generic: "diphenhydramine",
    brand: "Benadryl",
    category: "Anticholinergics & Antihistamines",
    isFrid: true,
    fridClassId: "anticholinergics",
    defaultDose: "25mg",
    doseOptions: ["12.5mg", "25mg", "50mg"],
    defaultFreq: "PRN",
    freqOptions: ["PRN", "QHS PRN", "Q6H PRN", "QHS"],
    route: "PO",
    beersWarning: "High anticholinergic burden (ACB +3): precipitating delirium, acute urinary retention, dry mouth, and confusion.",
    acbScore: 3,
  },
  {
    id: "hydroxyzine",
    name: "Hydroxyzine",
    generic: "hydroxyzine",
    brand: "Vistaril / Atarax",
    category: "Anticholinergics & Antihistamines",
    isFrid: true,
    fridClassId: "anticholinergics",
    defaultDose: "25mg",
    doseOptions: ["10mg", "25mg", "50mg"],
    defaultFreq: "PRN",
    freqOptions: ["PRN", "QHS", "TID PRN"],
    route: "PO",
    beersWarning: "Sedating H1-blocker with potent central antimuscarinic activity.",
    acbScore: 3,
  },
  {
    id: "promethazine",
    name: "Promethazine",
    generic: "promethazine",
    brand: "Phenergan",
    category: "Anticholinergics & Antihistamines",
    isFrid: true,
    fridClassId: "anticholinergics",
    defaultDose: "12.5mg",
    doseOptions: ["12.5mg", "25mg"],
    defaultFreq: "PRN",
    freqOptions: ["PRN", "Q6H PRN", "QHS"],
    route: "PO",
    beersWarning: "Significant extrapyramidal symptoms, sedation, and delirium risk.",
    acbScore: 3,
  },
  {
    id: "meclizine",
    name: "Meclizine",
    generic: "meclizine",
    brand: "Antivert",
    category: "Anticholinergics & Antihistamines",
    isFrid: true,
    fridClassId: "anticholinergics",
    defaultDose: "25mg",
    doseOptions: ["12.5mg", "25mg", "50mg"],
    defaultFreq: "TID",
    freqOptions: ["TID", "BID", "PRN"],
    route: "PO",
    beersWarning: "High anticholinergic load often paradoxically worsening vestibular ataxia.",
    acbScore: 2,
  },
  {
    id: "oxybutynin",
    name: "Oxybutynin",
    generic: "oxybutynin",
    brand: "Ditropan",
    category: "Anticholinergics & Antihistamines",
    isFrid: true,
    fridClassId: "anticholinergics",
    defaultDose: "5mg",
    doseOptions: ["2.5mg", "5mg", "10mg XL"],
    defaultFreq: "BID",
    freqOptions: ["BID", "TID", "Daily (XL)"],
    route: "PO",
    beersWarning: "High CNS penetration antimuscarinic: doubles cognitive decline rate.",
    acbScore: 3,
  },

  // 4. Vasodilators & Alpha-Blockers (FRID: vasodilators)
  {
    id: "hydralazine",
    name: "Hydralazine",
    generic: "hydralazine",
    brand: "Apresoline",
    category: "Vasodilators & Alpha-Blockers",
    isFrid: true,
    fridClassId: "vasodilators",
    defaultDose: "25mg",
    doseOptions: ["10mg", "25mg", "50mg"],
    defaultFreq: "TID",
    freqOptions: ["TID", "BID", "QID"],
    route: "PO",
    beersWarning: "Direct arterial smooth muscle relaxation: abrupt systolic orthostatic drop upon standing.",
  },
  {
    id: "nitroglycerin",
    name: "Nitroglycerin",
    generic: "nitroglycerin",
    brand: "Nitrostat / Nitro-Dur",
    category: "Vasodilators & Alpha-Blockers",
    isFrid: true,
    fridClassId: "vasodilators",
    defaultDose: "0.4mg",
    doseOptions: ["0.3mg", "0.4mg", "0.2mg/hr patch", "0.4mg/hr patch"],
    defaultFreq: "PRN",
    freqOptions: ["PRN", "Daily (Patch on AM, off PM)"],
    route: "SL",
    beersWarning: "Systemic venous pooling and sudden baroreceptor syncope.",
  },
  {
    id: "isosorbide",
    name: "Isosorbide Mononitrate",
    generic: "isosorbide mononitrate",
    brand: "Imdur",
    category: "Vasodilators & Alpha-Blockers",
    isFrid: true,
    fridClassId: "vasodilators",
    defaultDose: "30mg",
    doseOptions: ["30mg", "60mg", "120mg"],
    defaultFreq: "QAM",
    freqOptions: ["QAM", "Daily"],
    route: "PO",
    beersWarning: "Continuous nitrate dilation causing postural orthostasis.",
  },
  {
    id: "prazosin",
    name: "Prazosin",
    generic: "prazosin",
    brand: "Minipress",
    category: "Vasodilators & Alpha-Blockers",
    isFrid: true,
    fridClassId: "vasodilators",
    defaultDose: "1mg",
    doseOptions: ["1mg", "2mg", "5mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "BID"],
    route: "PO",
    beersWarning: "Peripheral alpha-1 blocker: severe first-dose postural syncope.",
  },
  {
    id: "clonidine",
    name: "Clonidine",
    generic: "clonidine",
    brand: "Catapres",
    category: "Vasodilators & Alpha-Blockers",
    isFrid: true,
    fridClassId: "vasodilators",
    defaultDose: "0.1mg",
    doseOptions: ["0.1mg", "0.2mg", "0.3mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "TID", "QHS"],
    route: "PO",
    beersWarning: "Central alpha-2 agonist: severe CNS sedation, bradycardia, and orthostatic hypotension.",
  },

  // 5. Opioids (FRID: opioids)
  {
    id: "morphine",
    name: "Morphine",
    generic: "morphine",
    brand: "MS Contin / Roxanol",
    category: "Opioids & Central Analgesics",
    isFrid: true,
    fridClassId: "opioids",
    defaultDose: "15mg",
    doseOptions: ["7.5mg", "15mg", "30mg"],
    defaultFreq: "Q4H PRN",
    freqOptions: ["Q4H PRN", "Q12H", "BID"],
    route: "PO",
    beersWarning: "Active neurotoxic M3G/M6G metabolites accumulate in renal impairment (eGFR < 45).",
  },
  {
    id: "oxycodone",
    name: "Oxycodone",
    generic: "oxycodone",
    brand: "Roxicodone / OxyContin",
    category: "Opioids & Central Analgesics",
    isFrid: true,
    fridClassId: "opioids",
    defaultDose: "5mg",
    doseOptions: ["2.5mg", "5mg", "10mg"],
    defaultFreq: "Q4H PRN",
    freqOptions: ["Q4H PRN", "Q6H PRN", "Q12H"],
    route: "PO",
    beersWarning: "CNS sedation and respiratory depression amplified when combined with sedatives.",
  },
  {
    id: "hydromorphone",
    name: "Hydromorphone",
    generic: "hydromorphone",
    brand: "Dilaudid",
    category: "Opioids & Central Analgesics",
    isFrid: true,
    fridClassId: "opioids",
    defaultDose: "2mg",
    doseOptions: ["1mg", "2mg", "4mg"],
    defaultFreq: "Q4H PRN",
    freqOptions: ["Q4H PRN", "Q6H PRN"],
    route: "PO",
    beersWarning: "High-potency mu-agonist: rapid sedation and motor ataxia.",
  },
  {
    id: "fentanyl",
    name: "Fentanyl",
    generic: "fentanyl",
    brand: "Duragesic",
    category: "Opioids & Central Analgesics",
    isFrid: true,
    fridClassId: "opioids",
    defaultDose: "25mcg/hr",
    doseOptions: ["12mcg/hr", "25mcg/hr", "50mcg/hr"],
    defaultFreq: "Q72H",
    freqOptions: ["Q72H (Patch)"],
    route: "Patch",
    beersWarning: "Continuous transdermal absorption: severe risk in cachectic or febrile older adults.",
  },
  {
    id: "tramadol",
    name: "Tramadol",
    generic: "tramadol",
    brand: "Ultram",
    category: "Opioids & Central Analgesics",
    isFrid: true,
    fridClassId: "opioids",
    defaultDose: "50mg",
    doseOptions: ["25mg", "50mg", "100mg"],
    defaultFreq: "Q6H PRN",
    freqOptions: ["Q6H PRN", "TID PRN", "BID"],
    route: "PO",
    beersWarning: "Dual opioid + SNRI action: high risk of SIADH, hyponatremia, seizures, and delirium.",
  },

  // 6. Antipsychotics (FRID: antipsychotics)
  {
    id: "haloperidol",
    name: "Haloperidol",
    generic: "haloperidol",
    brand: "Haldol",
    category: "Antipsychotics",
    isFrid: true,
    fridClassId: "antipsychotics",
    defaultDose: "0.5mg",
    doseOptions: ["0.5mg", "1.0mg", "2.0mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "QHS", "PRN"],
    route: "PO",
    beersWarning: "Black Box Warning: increased mortality in elderly dementia patients. Severe EPS and Parkinsonian gait freezing.",
  },
  {
    id: "quetiapine",
    name: "Quetiapine",
    generic: "quetiapine",
    brand: "Seroquel",
    category: "Antipsychotics",
    isFrid: true,
    fridClassId: "antipsychotics",
    defaultDose: "25mg",
    doseOptions: ["12.5mg", "25mg", "50mg", "100mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "BID", "TID"],
    route: "PO",
    beersWarning: "Antagonizes H1 and alpha-1 receptors: profound nocturnal sedation and orthostasis.",
  },
  {
    id: "risperidone",
    name: "Risperidone",
    generic: "risperidone",
    brand: "Risperdal",
    category: "Antipsychotics",
    isFrid: true,
    fridClassId: "antipsychotics",
    defaultDose: "0.5mg",
    doseOptions: ["0.25mg", "0.5mg", "1.0mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "QHS", "Daily"],
    route: "PO",
    beersWarning: "Postural instability and hyperprolactinemia.",
  },
  {
    id: "olanzapine",
    name: "Olanzapine",
    generic: "olanzapine",
    brand: "Zyprexa",
    category: "Antipsychotics",
    isFrid: true,
    fridClassId: "antipsychotics",
    defaultDose: "5mg",
    doseOptions: ["2.5mg", "5mg", "10mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "Daily"],
    route: "PO",
    beersWarning: "Anticholinergic + sedating profile.",
  },
  {
    id: "aripiprazole",
    name: "Aripiprazole",
    generic: "aripiprazole",
    brand: "Abilify",
    category: "Antipsychotics",
    isFrid: true,
    fridClassId: "antipsychotics",
    defaultDose: "5mg",
    doseOptions: ["2mg", "5mg", "10mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM"],
    route: "PO",
    beersWarning: "Akathisia and motor restlessness predisposing to unassisted transfer falls.",
  },

  // 7. Sedating Antidepressants & TCAs (FRID: tca)
  {
    id: "trazodone",
    name: "Trazodone",
    generic: "trazodone",
    brand: "Desyrel",
    category: "Sedating Antidepressants & TCAs",
    isFrid: true,
    fridClassId: "tca",
    defaultDose: "50mg",
    doseOptions: ["25mg", "50mg", "100mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "PRN QHS"],
    route: "PO",
    beersWarning: "Alpha-1 blockade causing dramatic nighttime orthostatic blood pressure drops.",
  },
  {
    id: "mirtazapine",
    name: "Mirtazapine",
    generic: "mirtazapine",
    brand: "Remeron",
    category: "Sedating Antidepressants & TCAs",
    isFrid: true,
    fridClassId: "tca",
    defaultDose: "15mg",
    doseOptions: ["7.5mg", "15mg", "30mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS"],
    route: "PO",
    beersWarning: "Lower doses (7.5-15mg) are intensely sedating via central H1 blockade.",
  },
  {
    id: "amitriptyline",
    name: "Amitriptyline",
    generic: "amitriptyline",
    brand: "Elavil",
    category: "Sedating Antidepressants & TCAs",
    isFrid: true,
    fridClassId: "tca",
    defaultDose: "25mg",
    doseOptions: ["10mg", "25mg", "50mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS"],
    route: "PO",
    beersWarning: "Avoid: highly anticholinergic (ACB +3), sedating, causes orthostatic syncope.",
    acbScore: 3,
  },
  {
    id: "paroxetine",
    name: "Paroxetine",
    generic: "paroxetine",
    brand: "Paxil",
    category: "Sedating Antidepressants & TCAs",
    isFrid: true,
    fridClassId: "tca",
    defaultDose: "20mg",
    doseOptions: ["10mg", "20mg", "40mg"],
    defaultFreq: "QAM",
    freqOptions: ["QAM", "Daily"],
    route: "PO",
    beersWarning: "Highest anticholinergic burden among all SSRIs (ACB +3).",
    acbScore: 3,
  },

  // 8. Antiepileptics / Neuropathics (FRID: antiepileptics)
  {
    id: "gabapentin",
    name: "Gabapentin",
    generic: "gabapentin",
    brand: "Neurontin",
    category: "Antiepileptics & Neuropathics",
    isFrid: true,
    fridClassId: "antiepileptics",
    defaultDose: "300mg",
    doseOptions: ["100mg", "300mg", "600mg"],
    defaultFreq: "TID",
    freqOptions: ["TID", "BID", "QHS"],
    route: "PO",
    beersWarning: "Requires 100% renal dose adjustments. Synergizes with sedatives to induce gross limb ataxia.",
  },
  {
    id: "pregabalin",
    name: "Pregabalin",
    generic: "pregabalin",
    brand: "Lyrica",
    category: "Antiepileptics & Neuropathics",
    isFrid: true,
    fridClassId: "antiepileptics",
    defaultDose: "75mg",
    doseOptions: ["25mg", "50mg", "75mg", "150mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "TID"],
    route: "PO",
    beersWarning: "Marked peripheral edema and vestibulo-cerebellar imbalance.",
  },
  {
    id: "carbamazepine",
    name: "Carbamazepine",
    generic: "carbamazepine",
    brand: "Tegretol",
    category: "Antiepileptics & Neuropathics",
    isFrid: true,
    fridClassId: "antiepileptics",
    defaultDose: "200mg",
    doseOptions: ["100mg", "200mg", "400mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "TID"],
    route: "PO",
    beersWarning: "High risk of SIADH hyponatremia and CYP3A4 auto-induction.",
  },
  {
    id: "levetiracetam",
    name: "Levetiracetam",
    generic: "levetiracetam",
    brand: "Keppra",
    category: "Antiepileptics & Neuropathics",
    isFrid: true,
    fridClassId: "antiepileptics",
    defaultDose: "500mg",
    doseOptions: ["250mg", "500mg", "1000mg"],
    defaultFreq: "BID",
    freqOptions: ["BID"],
    route: "PO",
    beersWarning: "CNS somnolence, asthenia, and behavioral irritation in elders.",
  },

  // 9. Essential Baseline Geriatric & Cardiovascular Medications
  {
    id: "metoprolol",
    name: "Metoprolol",
    generic: "metoprolol",
    brand: "Lopressor / Toprol-XL",
    category: "Beta-Blockers",
    isFrid: false,
    defaultDose: "25mg",
    doseOptions: ["12.5mg", "25mg", "50mg", "100mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "Daily (XL)"],
    route: "PO",
  },
  {
    id: "lisinopril",
    name: "Lisinopril",
    generic: "lisinopril",
    brand: "Zestril / Prinivil",
    category: "ACE Inhibitors",
    isFrid: false,
    defaultDose: "10mg",
    doseOptions: ["2.5mg", "5mg", "10mg", "20mg", "40mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM"],
    route: "PO",
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    generic: "amlodipine",
    brand: "Norvasc",
    category: "Calcium Channel Blockers",
    isFrid: false,
    defaultDose: "5mg",
    doseOptions: ["2.5mg", "5mg", "10mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM"],
    route: "PO",
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin",
    generic: "atorvastatin",
    brand: "Lipitor",
    category: "Statins",
    isFrid: false,
    defaultDose: "20mg",
    doseOptions: ["10mg", "20mg", "40mg", "80mg"],
    defaultFreq: "QHS",
    freqOptions: ["QHS", "Daily"],
    route: "PO",
  },
  {
    id: "omeprazole",
    name: "Omeprazole",
    generic: "omeprazole",
    brand: "Prilosec",
    category: "Proton Pump Inhibitors",
    isFrid: false,
    defaultDose: "20mg",
    doseOptions: ["20mg", "40mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM AC", "BID"],
    route: "PO",
  },
  {
    id: "pantoprazole",
    name: "Pantoprazole",
    generic: "pantoprazole",
    brand: "Protonix",
    category: "Proton Pump Inhibitors",
    isFrid: false,
    defaultDose: "40mg",
    doseOptions: ["20mg", "40mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM AC", "BID"],
    route: "PO",
  },
  {
    id: "metformin",
    name: "Metformin",
    generic: "metformin",
    brand: "Glucophage",
    category: "Antidiabetics",
    isFrid: false,
    defaultDose: "500mg",
    doseOptions: ["500mg", "850mg", "1000mg"],
    defaultFreq: "BID",
    freqOptions: ["BID", "Daily", "TID"],
    route: "PO",
  },
  {
    id: "aspirin",
    name: "Aspirin",
    generic: "aspirin",
    brand: "Bayer",
    category: "Antiplatelets",
    isFrid: false,
    defaultDose: "81mg",
    doseOptions: ["81mg", "325mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM"],
    route: "PO",
  },
  {
    id: "acetaminophen",
    name: "Acetaminophen",
    generic: "acetaminophen",
    brand: "Tylenol",
    category: "Analgesics / Antipyretics",
    isFrid: false,
    defaultDose: "650mg",
    doseOptions: ["325mg", "500mg", "650mg", "1000mg"],
    defaultFreq: "Q6H PRN",
    freqOptions: ["Q6H PRN", "TID PRN", "BID", "Daily"],
    route: "PO",
  },
  {
    id: "apixaban",
    name: "Apixaban",
    generic: "apixaban",
    brand: "Eliquis",
    category: "DOAC Anticoagulants",
    isFrid: false,
    defaultDose: "5mg",
    doseOptions: ["2.5mg", "5mg"],
    defaultFreq: "BID",
    freqOptions: ["BID"],
    route: "PO",
  },
  {
    id: "warfarin",
    name: "Warfarin",
    generic: "warfarin",
    brand: "Coumadin",
    category: "Anticoagulants",
    isFrid: false,
    defaultDose: "5mg",
    doseOptions: ["1mg", "2mg", "2.5mg", "5mg", "7.5mg"],
    defaultFreq: "QPM",
    freqOptions: ["QPM", "Daily"],
    route: "PO",
  },
  {
    id: "diltiazem",
    name: "Diltiazem",
    generic: "diltiazem",
    brand: "Cardizem",
    category: "Calcium Channel Blockers",
    isFrid: false,
    defaultDose: "120mg",
    doseOptions: ["30mg", "60mg", "120mg CD", "180mg CD", "240mg CD"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "TID", "QID"],
    route: "PO",
  },
  {
    id: "digoxin",
    name: "Digoxin",
    generic: "digoxin",
    brand: "Lanoxin",
    category: "Cardiac Glycosides",
    isFrid: false,
    defaultDose: "0.125mg",
    doseOptions: ["0.0625mg", "0.125mg", "0.25mg"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "QAM"],
    route: "PO",
    beersWarning: "Narrow therapeutic window. In CKD, clearance decreases substantially leading to severe toxicity.",
  },
  {
    id: "levothyroxine",
    name: "Levothyroxine",
    generic: "levothyroxine",
    brand: "Synthroid",
    category: "Thyroid Hormones",
    isFrid: false,
    defaultDose: "50mcg",
    doseOptions: ["25mcg", "50mcg", "75mcg", "88mcg", "100mcg"],
    defaultFreq: "QAM AC",
    freqOptions: ["QAM AC", "Daily"],
    route: "PO",
  },
  {
    id: "potassium_chloride",
    name: "Potassium Chloride",
    generic: "potassium chloride",
    brand: "K-Dur / Klor-Con",
    category: "Electrolyte Supplements",
    isFrid: false,
    defaultDose: "20mEq",
    doseOptions: ["10mEq", "20mEq", "40mEq"],
    defaultFreq: "Daily",
    freqOptions: ["Daily", "BID"],
    route: "PO",
  }
];

/**
 * Searches the curated database and returns ranked matching drug options.
 */
export function searchCuratedDrugs(query: string, limit: number = 10): CuratedDrug[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return CURATED_DRUG_DATABASE.slice(0, limit);
  }

  const exactMatches: CuratedDrug[] = [];
  const startsWithMatches: CuratedDrug[] = [];
  const containsMatches: CuratedDrug[] = [];

  for (const drug of CURATED_DRUG_DATABASE) {
    const gen = drug.generic.toLowerCase();
    const brand = drug.brand?.toLowerCase() || "";
    const name = drug.name.toLowerCase();

    if (gen === q || brand === q || name === q) {
      exactMatches.push(drug);
    } else if (gen.startsWith(q) || brand.startsWith(q) || name.startsWith(q)) {
      startsWithMatches.push(drug);
    } else if (gen.includes(q) || brand.includes(q) || drug.category.toLowerCase().includes(q)) {
      containsMatches.push(drug);
    }
  }

  const combined = [...exactMatches, ...startsWithMatches, ...containsMatches];
  return combined.slice(0, limit);
}
