import { Patient, WardKpis, WardDistribution } from "@/types/patient";

export const INITIAL_WARD_KPIS: WardKpis = {
  high_fall_risk_count: 11,
  high_fall_risk_today_delta: 2,
  acute_admissions_flagged_12h: 3,
  active_pim_alerts_count: 19,
  stopp_version: "STOPP v3",
  commonest_pim_type: "CNS Polypharmacy & Sedatives",
  severe_ddi_burden_count: 8,
  critical_interaction_index: 62,
  ddi_synergies_desc: "Additive orthostatic & sedative synergies",
  deprescribing_completed_pct: 74.2,
  deprescribing_week_delta: 12,
  medication_tapers_week_count: 26,
};

export const INITIAL_WARD_DISTRIBUTION: WardDistribution = {
  total_inpatients: 48,
  stratums: [
    {
      id: "critical",
      label: "Critical",
      criteria: ">60%",
      patient_count: 3,
      percentage: 6.3,
      color_class: "bg-[#ef4444]",
      bar_color: "#ef4444",
    },
    {
      id: "high",
      label: "High Risk",
      criteria: "41-60%",
      patient_count: 8,
      percentage: 16.7,
      color_class: "bg-[#f59e0b]",
      bar_color: "#f59e0b",
    },
    {
      id: "moderate",
      label: "Moderate",
      criteria: "20-40%",
      patient_count: 19,
      percentage: 39.6,
      color_class: "bg-[#0d9488]",
      bar_color: "#0d9488",
    },
    {
      id: "minimal",
      label: "Minimal",
      criteria: "<20%",
      patient_count: 18,
      percentage: 37.5,
      color_class: "bg-[#94a3b8]",
      bar_color: "#94a3b8",
    },
  ],
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    hadm_id: 884210,
    mrn: "MRN: #884210",
    name: "Eleanor Vance",
    initials: "EV",
    age: 84,
    gender: "FEMALE",
    bed: "Bed 402-A",
    ward: "Acute Care Unit 4B",
    los_days: 1,
    code_status: "Full Code",
    acuity_tier: "Critical",
    risk_percentage: 68.4,
    trend: "up",
    drug_count: 16,
    prn_count: 3,
    creatinine: 1.80,
    renal_egfr: 28,
    renal_stage: "CKD 4",
    blood_pressure: "114/68",
    bp_drop: -22,
    primary_pim: { label: "Z-Drug (Zolpidem 10mg)", severity: "critical" },
    secondary_pim: "Diuretic (Furosemide 40mg)",
    high_risk_meds: ["Z-Drug (Zolpidem 10mg)", "Diuretic (Furosemide 40mg)"],
    primary_recommendation: "Taper Zolpidem; initiate sleep hygiene protocol",
    recommendation_tags: "(BEERS 2023: HIGH SEDATION RISK)",
    review_badge: "Unreviewed",
    review_time: "Admitted 2h ago",
    reviewer_info: "Admitted 2h ago",
  },
  {
    hadm_id: 773194,
    mrn: "MRN: #773194",
    name: "Arthur Pendelton",
    initials: "AP",
    age: 79,
    gender: "MALE",
    bed: "Bed 404-B",
    ward: "Acute Care Unit 4B",
    los_days: 2,
    code_status: "Full Code",
    acuity_tier: "Critical",
    risk_percentage: 58.2,
    trend: "up",
    drug_count: 14,
    prn_count: 2,
    creatinine: 1.50,
    renal_egfr: 34,
    renal_stage: "CKD 3b",
    blood_pressure: "118/70",
    bp_drop: -18,
    primary_pim: { label: "BZD (Lorazepam 1mg)", severity: "critical" },
    secondary_pim: "Loop Diuretic (PM Dose)",
    high_risk_meds: ["BZD (Lorazepam 1mg)", "Loop Diuretic (PM Dose)"],
    primary_recommendation: "Deprescribe Furosemide PM; switch to AM to eliminate nocturia-related fall hazard",
    recommendation_tags: "",
    review_time: "Reviewed 45m ago by Dr. Chen",
    review_actor: "by Dr. Chen",
    reviewer_info: "Reviewed 45m ago by Dr. Chen",
  },
  {
    hadm_id: 642109,
    mrn: "MRN: #642109",
    name: "Clara Higgins",
    initials: "CH",
    age: 88,
    gender: "FEMALE",
    bed: "Bed 407-A",
    ward: "Acute Care Unit 4B",
    los_days: 3,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 44.7,
    trend: "up",
    drug_count: 12,
    prn_count: 1,
    creatinine: 1.10,
    renal_egfr: 58,
    renal_stage: "Normal",
    blood_pressure: "126/74",
    bp_drop: -15,
    primary_pim: { label: "Anticholinergic (ACB 3)", severity: "high" },
    secondary_pim: "Diphenhydramine",
    high_risk_meds: ["Anticholinergic (ACB 3)", "Diphenhydramine"],
    primary_recommendation: "Anticholinergic reduction (ACB score 3 → 1); alert for delirium precursor",
    recommendation_tags: "",
    review_time: "Reviewed 2h ago by PharmD Vance",
    review_actor: "by PharmD Vance",
    reviewer_info: "Reviewed 2h ago by PharmD Vance",
  },
  {
    hadm_id: 559021,
    mrn: "MRN: #559021",
    name: "Walter Kowalski",
    initials: "WK",
    age: 81,
    gender: "MALE",
    bed: "Bed 410-C",
    ward: "Acute Care Unit 4B",
    los_days: 4,
    code_status: "DNR/DNI",
    acuity_tier: "High",
    risk_percentage: 42.1,
    trend: "up",
    drug_count: 15,
    prn_count: 4,
    creatinine: 2.10,
    renal_egfr: 24,
    renal_stage: "CKD 4",
    blood_pressure: "110/65",
    bp_drop: -20,
    primary_pim: { label: "Opioid (Oxycodone 5mg)", severity: "high" },
    secondary_pim: "Gabapentin 300mg",
    high_risk_meds: ["Opioid (Oxycodone 5mg)", "Gabapentin 300mg"],
    primary_recommendation: "Renal dose adjust Gabapentin to 100mg QHS; monitor accumulation ataxia",
    recommendation_tags: "",
    review_time: "Reviewed 3h ago by Dr. Chen",
    review_actor: "by Dr. Chen",
    reviewer_info: "Reviewed 3h ago by Dr. Chen",
  },
  {
    hadm_id: 902143,
    mrn: "MRN: #902143",
    name: "Margaret DuPont",
    initials: "MD",
    age: 76,
    gender: "FEMALE",
    bed: "Bed 412-B",
    ward: "Acute Care Unit 4B",
    los_days: 3,
    code_status: "Full Code",
    acuity_tier: "Moderate",
    risk_percentage: 21.5,
    trend: "neutral",
    drug_count: 9,
    prn_count: 1,
    creatinine: 0.90,
    renal_egfr: 72,
    renal_stage: "Preserved",
    blood_pressure: "134/78",
    bp_drop: -14,
    primary_pim: { label: "Antihypertensive (Amlodipine)", severity: "neutral" },
    high_risk_meds: ["Antihypertensive (Amlodipine)"],
    primary_recommendation: "Monitor seated/standing blood pressure delta; postural stability check passed",
    recommendation_tags: "",
    review_time: "Reviewed 5h ago by RN Sarah",
    review_actor: "by RN Sarah",
    reviewer_info: "Reviewed 5h ago by RN Sarah",
  },
  {
    hadm_id: 431872,
    mrn: "MRN: #431872",
    name: "Harold Jenkins",
    initials: "HJ",
    age: 73,
    gender: "MALE",
    bed: "Bed 415-A",
    ward: "Acute Care Unit 4B",
    los_days: 5,
    code_status: "Full Code",
    acuity_tier: "Low",
    risk_percentage: 14.3,
    trend: "down",
    drug_count: 6,
    prn_count: 0,
    creatinine: 0.80,
    renal_egfr: 88,
    renal_stage: "Normal",
    blood_pressure: "122/74",
    bp_drop: -4,
    primary_pim: { label: "Statin + Beta-Blocker", severity: "neutral" },
    high_risk_meds: ["Statin + Beta-Blocker"],
    primary_recommendation: "Optimal regimen maintained; discharge review scheduled",
    recommendation_tags: "",
    review_time: "Reviewed 6h ago (Discharge ready)",
    review_actor: "(Discharge ready)",
    reviewer_info: "Reviewed 6h ago (Discharge ready)",
  },
  // Additional patients from Ward 4B census
  {
    hadm_id: 994211,
    mrn: "#MRN-80101",
    name: "Clara Oswald",
    initials: "CO",
    age: 79,
    gender: "FEMALE",
    bed: "Bed 402-A",
    ward: "Geriatric Ward 4B",
    los_days: 2,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 48.5,
    trend: "up",
    drug_count: 11,
    prn_count: 2,
    creatinine: 1.45,
    renal_egfr: 41,
    renal_stage: "CKD 3b",
    blood_pressure: "119/72",
    bp_drop: -16,
    primary_pim: { label: "Z-Drug (Zolpidem 5mg)", severity: "high" },
    secondary_pim: "Furosemide 20mg",
    high_risk_meds: ["Zolpidem 5mg", "Furosemide 20mg"],
    primary_recommendation: "Z-Drug fall risk flagged; taper to sleep hygiene protocol",
    recommendation_tags: "BEERS 2023 · SEDATION HAZARD",
    review_time: "Reviewed 3h ago",
    review_actor: "By Staff RN",
    reviewer_info: "Reviewed 3h ago By Staff RN",
  },
  {
    hadm_id: 994212,
    mrn: "#MRN-80102",
    name: "George Gale",
    initials: "GG",
    age: 85,
    gender: "MALE",
    bed: "Bed 402-B",
    ward: "Geriatric Ward 4B",
    los_days: 3,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 54.2,
    trend: "up",
    drug_count: 13,
    prn_count: 1,
    creatinine: 1.60,
    renal_egfr: 36,
    renal_stage: "CKD 3b",
    blood_pressure: "125/70",
    bp_drop: -17,
    primary_pim: { label: "Antipsychotic + BZD", severity: "critical" },
    secondary_pim: "Haloperidol 0.5mg",
    high_risk_meds: ["Haloperidol 0.5mg", "Clonazepam"],
    primary_recommendation: "Antipsychotic + Benzodiazepine synergism; ataxia alert",
    recommendation_tags: "HIGH EXTRAPYRAMIDAL RISK",
    review_time: "Reviewed 4h ago",
    review_actor: "By Dr. Chen",
    reviewer_info: "Reviewed 4h ago By Dr. Chen",
  },
  {
    hadm_id: 994213,
    mrn: "#MRN-80103",
    name: "Beatrice Montgomery",
    initials: "BM",
    age: 82,
    gender: "FEMALE",
    bed: "Bed 403-A",
    ward: "Geriatric Ward 4B",
    los_days: 4,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 42.1,
    trend: "up",
    drug_count: 10,
    prn_count: 0,
    creatinine: 1.30,
    renal_egfr: 48,
    renal_stage: "CKD 3a",
    blood_pressure: "128/76",
    bp_drop: -14,
    primary_pim: { label: "Opioid + Gabapentinoid", severity: "high" },
    secondary_pim: "Oxycodone 5mg",
    high_risk_meds: ["Oxycodone 5mg", "Pregabalin"],
    primary_recommendation: "Opioid + Gabapentinoid sedation alert; bedside fall alarm activated",
    recommendation_tags: "STOPP SEC K · SEDATION",
    review_time: "Reviewed 1h ago",
    review_actor: "By RN Sarah",
    reviewer_info: "Reviewed 1h ago By RN Sarah",
  },
  {
    hadm_id: 994214,
    mrn: "#MRN-80104",
    name: "Donald Fletcher",
    initials: "DF",
    age: 77,
    gender: "MALE",
    bed: "Bed 403-B",
    ward: "Geriatric Ward 4B",
    los_days: 1,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 46.8,
    trend: "up",
    drug_count: 12,
    prn_count: 2,
    creatinine: 1.55,
    renal_egfr: 38,
    renal_stage: "CKD 3b",
    blood_pressure: "116/68",
    bp_drop: -19,
    primary_pim: { label: "Diuretic + BZD", severity: "high" },
    secondary_pim: "Temazepam",
    high_risk_meds: ["Hydrochlorothiazide", "Temazepam"],
    primary_recommendation: "Diuretic volume depletion + BZD; standing drop -19 mmHg",
    recommendation_tags: "ORTHOSTATIC HYPOTENSION ALERT",
    review_time: "Reviewed 5h ago",
    review_actor: "By Staff RN",
    reviewer_info: "Reviewed 5h ago By Staff RN",
  },
  {
    hadm_id: 994215,
    mrn: "#MRN-80105",
    name: "Florence Davis",
    initials: "FD",
    age: 88,
    gender: "FEMALE",
    bed: "Bed 404-A",
    ward: "Geriatric Ward 4B",
    los_days: 5,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 59.4,
    trend: "up",
    drug_count: 14,
    prn_count: 3,
    creatinine: 1.70,
    renal_egfr: 32,
    renal_stage: "CKD 3b",
    blood_pressure: "112/66",
    bp_drop: -21,
    primary_pim: { label: "Alprazolam 0.5mg", severity: "critical" },
    secondary_pim: "Furosemide",
    high_risk_meds: ["Alprazolam 0.5mg", "Furosemide"],
    primary_recommendation: "Severe Beers PIM violation; pharmacist consult for taper",
    recommendation_tags: "BEERS CRITERIA CRITICAL",
    review_time: "Reviewed 2h ago",
    review_actor: "By PharmD Vance",
    reviewer_info: "Reviewed 2h ago By PharmD Vance",
  },
  {
    hadm_id: 994216,
    mrn: "#MRN-80106",
    name: "Samuel Brooks",
    initials: "SB",
    age: 83,
    gender: "MALE",
    bed: "Bed 404-B",
    ward: "Geriatric Ward 4B",
    los_days: 2,
    code_status: "Full Code",
    acuity_tier: "High",
    risk_percentage: 51.0,
    trend: "up",
    drug_count: 11,
    prn_count: 1,
    creatinine: 1.40,
    renal_egfr: 43,
    renal_stage: "CKD 3b",
    blood_pressure: "120/72",
    bp_drop: -16,
    primary_pim: { label: "Tamsulosin 0.4mg", severity: "high" },
    secondary_pim: "Lisinopril",
    high_risk_meds: ["Tamsulosin 0.4mg", "Lisinopril"],
    primary_recommendation: "Alpha-1 blocker first-dose syncope risk; monitor transfers",
    recommendation_tags: "NOCTURNAL SYNCOPE HAZARD",
    review_time: "Reviewed 3h ago",
    review_actor: "By Staff RN",
    reviewer_info: "Reviewed 3h ago By Staff RN",
  },
  {
    hadm_id: 994217,
    mrn: "#MRN-80107",
    name: "Alice Henderson",
    initials: "AH",
    age: 84,
    gender: "FEMALE",
    bed: "Bed 407-A",
    ward: "Geriatric Ward 4B",
    los_days: 3,
    code_status: "Full Code",
    acuity_tier: "Moderate",
    risk_percentage: 38.2,
    trend: "neutral",
    drug_count: 8,
    prn_count: 1,
    creatinine: 1.10,
    renal_egfr: 56,
    renal_stage: "CKD 3a",
    blood_pressure: "124/76",
    bp_drop: -13,
    primary_pim: { label: "SSRI (Citalopram 20mg)", severity: "warning" },
    high_risk_meds: ["Citalopram 20mg"],
    primary_recommendation: "QTc prolongation screening; PT gait assessment scheduled",
    recommendation_tags: "MONITOR HYPONATREMIA",
    review_time: "Reviewed 4h ago",
    review_actor: "By Staff RN",
    reviewer_info: "Reviewed 4h ago By Staff RN",
  },
  {
    hadm_id: 994218,
    mrn: "#MRN-80108",
    name: "Frank Castle",
    initials: "FC",
    age: 78,
    gender: "MALE",
    bed: "Bed 407-B",
    ward: "Geriatric Ward 4B",
    los_days: 1,
    code_status: "Full Code",
    acuity_tier: "Moderate",
    risk_percentage: 35.4,
    trend: "neutral",
    drug_count: 9,
    prn_count: 0,
    creatinine: 1.05,
    renal_egfr: 60,
    renal_stage: "CKD 2",
    blood_pressure: "126/78",
    bp_drop: -12,
    primary_pim: { label: "Carvedilol 12.5mg", severity: "neutral" },
    high_risk_meds: ["Carvedilol 12.5mg"],
    primary_recommendation: "Mild orthostatic sensation on chair stand; BP logged TID",
    recommendation_tags: "HEMODYNAMIC OBSERVATION",
    review_time: "Reviewed 5h ago",
    review_actor: "By RN Sarah",
    reviewer_info: "Reviewed 5h ago By RN Sarah",
  },
  {
    hadm_id: 994219,
    mrn: "#MRN-80109",
    name: "Henry Higgins",
    initials: "HH",
    age: 80,
    gender: "MALE",
    bed: "Bed 409-B",
    ward: "Geriatric Ward 4B",
    los_days: 4,
    code_status: "Full Code",
    acuity_tier: "Moderate",
    risk_percentage: 32.5,
    trend: "neutral",
    drug_count: 8,
    prn_count: 1,
    creatinine: 1.00,
    renal_egfr: 64,
    renal_stage: "CKD 2",
    blood_pressure: "130/74",
    bp_drop: -10,
    primary_pim: { label: "Losartan 50mg", severity: "neutral" },
    high_risk_meds: ["Losartan 50mg"],
    primary_recommendation: "Preserved balance score; routine discharge planning",
    recommendation_tags: "DISCHARGE PLANNING",
    review_time: "Reviewed 6h ago",
    review_actor: "By Dr. Chen",
    reviewer_info: "Reviewed 6h ago By Dr. Chen",
  },
  {
    hadm_id: 994220,
    mrn: "#MRN-80110",
    name: "Irene Adler",
    initials: "IA",
    age: 74,
    gender: "FEMALE",
    bed: "Bed 411-A",
    ward: "Geriatric Ward 4B",
    los_days: 2,
    code_status: "Full Code",
    acuity_tier: "Moderate",
    risk_percentage: 28.6,
    trend: "neutral",
    drug_count: 7,
    prn_count: 0,
    creatinine: 0.90,
    renal_egfr: 71,
    renal_stage: "CKD 2",
    blood_pressure: "122/70",
    bp_drop: -8,
    primary_pim: { label: "Levothyroxine 50mcg", severity: "neutral" },
    high_risk_meds: ["Levothyroxine", "Atorvastatin"],
    primary_recommendation: "Stable chronic pharmacotherapy; vitals within parameters",
    recommendation_tags: "STABLE REGIMEN",
    review_time: "Reviewed 7h ago",
    review_actor: "By Staff RN",
    reviewer_info: "Reviewed 7h ago By Staff RN",
  },
  {
    hadm_id: 994221,
    mrn: "#MRN-80111",
    name: "Xavier Rhodes",
    initials: "XR",
    age: 87,
    gender: "MALE",
    bed: "Bed 420-B",
    ward: "Geriatric Ward 4B",
    los_days: 5,
    code_status: "Full Code",
    acuity_tier: "Low",
    risk_percentage: 18.9,
    trend: "down",
    drug_count: 5,
    prn_count: 0,
    creatinine: 0.78,
    renal_egfr: 86,
    renal_stage: "CKD 1/2",
    blood_pressure: "118/72",
    bp_drop: -5,
    primary_pim: { label: "Atorvastatin 10mg", severity: "neutral" },
    high_risk_meds: ["Atorvastatin 10mg"],
    primary_recommendation: "Preserved functional independence; no fall history",
    recommendation_tags: "LOW RISK · INDEPENDENT",
    review_time: "Reviewed 8h ago",
    review_actor: "Discharge ready",
    reviewer_info: "Reviewed 8h ago Discharge ready",
  },
  {
    hadm_id: 994222,
    mrn: "#MRN-80112",
    name: "Audrey Hepburn",
    initials: "AH",
    age: 79,
    gender: "FEMALE",
    bed: "Bed 422-A",
    ward: "Geriatric Ward 4B",
    los_days: 4,
    code_status: "Full Code",
    acuity_tier: "Low",
    risk_percentage: 12.8,
    trend: "down",
    drug_count: 4,
    prn_count: 0,
    creatinine: 0.70,
    renal_egfr: 95,
    renal_stage: "CKD 1/2",
    blood_pressure: "120/70",
    bp_drop: -4,
    primary_pim: { label: "Cholecalciferol 1000IU", severity: "neutral" },
    high_risk_meds: ["Cholecalciferol 1000IU"],
    primary_recommendation: "Normal gait analysis; clear for home discharge",
    recommendation_tags: "DISCHARGE READY",
    review_time: "Reviewed 6h ago",
    review_actor: "Discharge ready",
    reviewer_info: "Reviewed 6h ago Discharge ready",
  },
  {
    hadm_id: 994223,
    mrn: "#MRN-80113",
    name: "James Dean",
    initials: "JD",
    age: 71,
    gender: "MALE",
    bed: "Bed 426-B",
    ward: "Geriatric Ward 4B",
    los_days: 3,
    code_status: "Full Code",
    acuity_tier: "Low",
    risk_percentage: 8.4,
    trend: "down",
    drug_count: 3,
    prn_count: 0,
    creatinine: 0.62,
    renal_egfr: 105,
    renal_stage: "CKD 1/2",
    blood_pressure: "115/68",
    bp_drop: -3,
    primary_pim: { label: "Acetaminophen PRN", severity: "neutral" },
    high_risk_meds: ["Acetaminophen PRN"],
    primary_recommendation: "Zero high-risk medications; discharge ready",
    recommendation_tags: "NO CDSS ALERTS ACTIVE",
    review_time: "Reviewed 7h ago",
    review_actor: "Discharge ready",
    reviewer_info: "Reviewed 7h ago Discharge ready",
  },
];
